### ISSUE TITLE
Side effect of highlighting all occurences of "[ ]" once task is marked as done

### ISSUE THREAD

**Issue by thegoodhen** [vitalk/vim-simple-todo#15]
If I type :nohlsearch afterwards, it gets fixed. I could probably do the necessary changes regarding this and the other issues I will post and send you a pull request?

**Comment by vitalk** [comment]
Please, see the #13. I wrote a little bit about my workflow with this plugin.

**Comment by thegoodhen** [comment]
Hello. Thanks for your reply. However, if you added :nohlsearch command, it would allow you to use n and N keys to jump between the remaining entries without highlighting them. Sorry I didn't see the duplicate, I didn't consider looking at the unresolved issues.

**Comment by vitalk** [comment]
> Sorry I didn't see the duplicate, I didn't consider looking at the
> unresolved issues.

This is my fault. I should be write about it in readme :smile: 

Please send me a pull request. If your implementation does not break default
behavior then I merge it into master.

**Comment by thegoodhen** [comment]
It's kinda getting late here, I'll look into it tomorrow! Thanks!

**Comment by yevhen-m** [comment]
Please, remove text highlighting after I mark a task done. 
It's not convenient for all users to do `nnore <esc><esc> :let @/ = ""<cr>` or do `:nohl` every time.

**Comment by kchu-activecampaign** [comment]
@vitalk If you add `:noh<cr>` at the end of (simple-todo-mark-as-done) command, wouldn't it meet your workflow AND clear out the search highlight?
