### ISSUE TITLE
No option to turn the current line into a task

### ISSUE THREAD

**Issue by thegoodhen** [vitalk/vim-simple-todo#16]
I had a TODO list as a raw list of lines before I found this nice plugin. :3
I wanted to add a TODO mark at the beginning of each line.

Suppose I have a line that says
Test line

but once I press 0 and \i

It turns into

T[ ] est line

Not into
[ ] Test line as expected

Obviously, workarounds exist, such as adding a dummy space on the beginning of each line.

**Comment by vitalk** [comment]
Hi, @thegoodhen. Thank you for the reporting!

This issue occurs because in insert mode, the cursor is between characters,
or before the first or after the last character. In normal mode, the cursor is
over a character.

This path allow to create a new todo when cursor at the beginning of the line.

**Comment by thegoodhen** [comment]
Oh wow, that was fast! Thank you very much!
