### ISSUE TITLE
Mark all selected lines as TODO items or if it is, mark as DONE

### ISSUE THREAD

**Issue by ovc** [vitalk/vim-simple-todo#21]
It will be useful if your script can mark all selected lines as TODO items or if it is, mark as DONE

**Comment by vitalk** [comment]
Hi @ovc!

You already can bulky update items (mark them as done/undone) in visual mode. But looks like I missed the feature to convert selected line into the todo item. Thank you, for pointing this.

Someday I'll implement the switch between different states via single key bindings.

**Comment by kchu-activecampaign** [comment]
Hello @vitalk , quick question

> You already can bulky update items (mark them as done/undone) in visual mode

How can I do this? I selected few todo lines and hit <leader>x but I got no range allowed error. Or did you mean we can use visual block mode to bulk update?

**Comment by vitalk** [comment]
Hi @kchu-activecampaign!

Looks like a bug and I try to fix it as soon as possible. As a workaround you can use `.` to repeat the last command (mark as done or undone) and `n`/`N` to navigate between items.

**Comment by kchu-activecampaign** [comment]
@vitalk Thanks for the tip. Workflow with `.` and `n/N` is really nice.
