### ISSUE TITLE
spacebar as Leader key conflicts with plugin mappings

### ISSUE THREAD

**Issue by hellostanley-zz** [vitalk/vim-simple-todo#39]
Is there a way to keep my leader key as the spacebar and use this plugin?

**Comment by kba** [comment]
Disable the standard key mappings with `let g:simple_todo_map_keys = 0` and define your own mappings. `:help simple-todo` shows you how.

**Comment by hellostanley-zz** [comment]
First, thanks for replying. I did the following:
```
let g:simple_todo_map_keys = 0
nmap <c-i> <Plug>(simple-todo-new)
nmap <c-o> <Plug>(simple-todo-below)
```
~~But still get the same problem, see demo below—seems to happy when I type (spacebar) fast while in insert mode (see <20> flashing-up)~~

I've now fixed it with 
`let g:simple_todo_map_insert_mode_keys = 0`
and replacing an ESC shortcut.

Thanks again for the help.

**Comment by vitalk** [comment]
Hi @hellostanley,

thank you for using the plugin. I hope the @kba helps you to solve this issue. Please reopen the issue if you have any other questions.
